insert into ved_yearlyevent (description,event_date) values ('NEW YEAR DAY (AMAVAS)','2015-01-01');
insert into ved_yearlyevent (description,event_date) values ('EKADASHI (PUTRADA)','2015-01-11');
insert into ved_yearlyevent (description,event_date) values ('SUNDAR KAND','2015-01-11');
insert into ved_yearlyevent (description,event_date) values ('LOHRI','2015-01-13');
insert into ved_yearlyevent (description,event_date) values ('MAGH SANKRANTI','2015-01-14');
insert into ved_yearlyevent (description,event_date) values ('POORNIMA & SATYANARAYAN VRAT','2015-01-15');
insert into ved_yearlyevent (description,event_date) values ('GANESH CHATURTHI','2015-01-19');
insert into ved_yearlyevent (description,event_date) values ('SANKATAHARA CHATURTHI','2015-01-19');
insert into ved_yearlyevent (description,event_date) values ('AMRIT VANI','2015-01-19');
insert into ved_yearlyevent (description,event_date) values ('EKADASHI (SHATILA)','2015-01-26');
insert into ved_yearlyevent (description,event_date) values ('REPUBLICDAY INDIA','2015-01-26');
insert into ved_yearlyevent (description,event_date) values ('MAUNI AMAVAS','2015-01-30');
insert into ved_yearlyevent (description,event_date) values ('GANESH TIL CHATURTHI','2015-02-02');
insert into ved_yearlyevent (description,event_date) values ('BASANT PANCHAMI','2015-02-03');
insert into ved_yearlyevent (description,event_date) values ('SARASWATI JAYANTI','2015-02-03');
insert into ved_yearlyevent (description,event_date) values ('SUNDAR KAND','2015-02-08');
insert into ved_yearlyevent (description,event_date) values ('EKADASHI (JAYA)','2015-02-10');
insert into ved_yearlyevent (description,event_date) values ('POORNIMA & SATYANARAYAN VRAT','2015-02-12');
insert into ved_yearlyevent (description,event_date) values ('SANKRANTI (FALGUN)','2015-02-12');
insert into ved_yearlyevent (description,event_date) values ('AMRIT VANI','2015-02-16');
insert into ved_yearlyevent (description,event_date) values ('GANESH CHATURTH','2015-02-18');
insert into ved_yearlyevent (description,event_date) values ('SANKATAHARA CHATURTHI','2015-02-18');
insert into ved_yearlyevent (description,event_date) values ('EKADASHI (VIJAYA)','2015-02-25');
insert into ved_yearlyevent (description,event_date) values ('MAHA SHIVRATRI','2015-02-27');
insert into ved_yearlyevent (description,event_date) values ('AMAVAS','2015-02-28');
insert into ved_yearlyevent (description,event_date) values ('AMRIT VANI ANNIVARSARY','2015-03-02');
insert into ved_yearlyevent (description,event_date) values ('HOLA ASHTAK BEGIN','2015-03-08');
insert into ved_yearlyevent (description,event_date) values ('SUNDAR KAND','2015-03-08');
insert into ved_yearlyevent (description,event_date) values ('EKDASHI (AMALAKI)','2015-03-11');
insert into ved_yearlyevent (description,event_date) values ('SANKRANTI (CHAITRA)','2015-03-14');
insert into ved_yearlyevent (description,event_date) values ('HOLIKA DAHAN','2015-03-16');
insert into ved_yearlyevent (description,event_date) values ('POORNIMA/SATYANARAYAN VRAT','2015-03-16');
insert into ved_yearlyevent (description,event_date) values ('GANESH CHATURTHI','2015-03-20');
insert into ved_yearlyevent (description,event_date) values ('SANKATAHARA CHATURTHI','2015-03-20');
insert into ved_yearlyevent (description,event_date) values ('SHEETALA ASHTAMI','2015-03-24');
insert into ved_yearlyevent (description,event_date) values ('EKADASHI (PAPMOCHINI)','2015-03-26');
insert into ved_yearlyevent (description,event_date) values ('AMAVAS','2015-03-30');
insert into ved_yearlyevent (description,event_date) values ('NAVRATRA BEGIN (SAMVAT 2071)','2015-03-31');
insert into ved_yearlyevent (description,event_date) values ('VISHAL BHAGWATI JAGRAN','2015-04-05');
insert into ved_yearlyevent (description,event_date) values ('DURGA ASHTAMI','2015-04-07');
insert into ved_yearlyevent (description,event_date) values ('SRI RAM NAVMI','2015-04-08');
insert into ved_yearlyevent (description,event_date) values ('EKADASHI (KAMADA)','2015-04-10');
insert into ved_yearlyevent (description,event_date) values ('AKHAND RAMAYAN','2015-04-12');
insert into ved_yearlyevent (description,event_date) values ('SUNDAR KAND','2015-04-12');
insert into ved_yearlyevent (description,event_date) values ('RAMAYAN BHOG','2015-04-13');
insert into ved_yearlyevent (description,event_date) values ('SANKRANTI (VAISAKH)','2015-04-14');
insert into ved_yearlyevent (description,event_date) values ('POORNIMA','2015-04-14');
insert into ved_yearlyevent (description,event_date) values ('HANUMAN JAYANTI (SOUTH)', '2015-04-15');
insert into ved_yearlyevent (description,event_date) values ('SANKATAHARA CHATURTHI','2015-04-18');
insert into ved_yearlyevent (description,event_date) values ('AMRIT VANI','2015-04-20');
insert into ved_yearlyevent (description,event_date) values ('EKADASHI (VARUTHINI)','2015-04-25');
insert into ved_yearlyevent (description,event_date) values ('AMAVAS','2015-04-28');
insert into ved_yearlyevent (description,event_date) values ('AKSHYA TRITIYA','2015-05-01');
insert into ved_yearlyevent (description,event_date) values ('SRI PARASHURAM JAYANTI','2015-05-01');
insert into ved_yearlyevent (description,event_date) values ('VISHNU SAHASRANAM PATH','2015-05-01');
insert into ved_yearlyevent (description,event_date) values ('SITA NAVAMI','2015-05-08');
insert into ved_yearlyevent (description,event_date) values ('EKDASHI (MOHINI)','2015-05-10');
insert into ved_yearlyevent (description,event_date) values ('SUNDAR KAND','2015-05-10');
insert into ved_yearlyevent (description,event_date) values ('POORNIMA','2015-05-14');
insert into ved_yearlyevent (description,event_date) values ('SANKRANTI (JYESHTHA','2015-05-14');
insert into ved_yearlyevent (description,event_date) values ('SATYANARAYAN VRAT','2015-05-14');
insert into ved_yearlyevent (description,event_date) values ('GANESH CHATURTHI','2015-05-17');
insert into ved_yearlyevent (description,event_date) values ('SANKATAHARA CHATURTHI','2015-05-17');
insert into ved_yearlyevent (description,event_date) values ('AMRIT VANI','2015-05-18');
insert into ved_yearlyevent (description,event_date) values ('EKADASHI (APARA)','2015-05-24');
insert into ved_yearlyevent (description,event_date) values ('AMAVAS','2015-05-28');
insert into ved_yearlyevent (description,event_date) values ('EKADASHI (NIRJALA)','2015-06-09');
insert into ved_yearlyevent (description,event_date) values ('POORNIMA','2015-06-12');
insert into ved_yearlyevent (description,event_date) values ('SATYANARAYAN VRAT','2015-06-12');
insert into ved_yearlyevent (description,event_date) values ('VATSAVITRI VRAT','2015-06-12');
insert into ved_yearlyevent (description,event_date) values ('SUNDAR KAND','2015-06-14');
insert into ved_yearlyevent (description,event_date) values ('AMRIT VANI','2015-06-15');
insert into ved_yearlyevent (description,event_date) values ('GANESH CHATURTHI','2015-06-15');
insert into ved_yearlyevent (description,event_date) values ('SANKRANTI (ASHAAD','2015-06-15');
insert into ved_yearlyevent (description,event_date) values ('SANKATAHARA CHATURTHI','2015-06-16');
insert into ved_yearlyevent (description,event_date) values ('EKADASHI (YOGINI)','2015-06-22');
insert into ved_yearlyevent (description,event_date) values ('GAYATRI MANTRA JAAP','2015-06-22');
insert into ved_yearlyevent (description,event_date) values ('AMAVAS','2015-06-26');
insert into ved_yearlyevent (description,event_date) values ('EKADASHI (DEVSHAYANI)','2015-07-08');
insert into ved_yearlyevent (description,event_date) values ('SATYA NARAYAN VRAT','2015-07-11');
insert into ved_yearlyevent (description,event_date) values ('','');
insert into ved_yearlyevent (description,event_date) values ('SUNDAR KAND','2015-07-12');
insert into ved_yearlyevent (description,event_date) values ('GANESH CHATURTHI','2015-07-14');
insert into ved_yearlyevent (description,event_date) values ('SANKATAHARA CHATURTHI','2015-07-15');
insert into ved_yearlyevent (description,event_date) values ('SANKRANTI (SHRAVAN)','2015-07-16');
insert into ved_yearlyevent (description,event_date) values ('AMRIT VANI','2015-07-20');
insert into ved_yearlyevent (description,event_date) values ('EKADASHI (KAMIIKA)','2015-07-22');
insert into ved_yearlyevent (description,event_date) values ('AMAVAS','2015-07-26');
insert into ved_yearlyevent (description,event_date) values ('MAHA MRITYUNJYA JAAP','2015-07-27');
insert into ved_yearlyevent (description,event_date) values ('HARIYALI TEEJ','2015-07-29');
insert into ved_yearlyevent (description,event_date) values ('NAG PANCHAMI','2015-07-31');
insert into ved_yearlyevent (description,event_date) values ('MAHA MRITYUNJYA HAVAN','2015-08-03');
insert into ved_yearlyevent (description,event_date) values ('EKADASHI (PAVITRA)','2015-08-06');
insert into ved_yearlyevent (description,event_date) values ('SATYANARAYAN VRAT','2015-08-09');
insert into ved_yearlyevent (description,event_date) values ('SUNDAR KAND','2015-08-09');
insert into ved_yearlyevent (description,event_date) values ('AMRIT VANI','2015-08-10');
insert into ved_yearlyevent (description,event_date) values ('POORNIMA','2015-08-10');
insert into ved_yearlyevent (description,event_date) values ('RAKSHA BANDHAN','2015-08-10');
insert into ved_yearlyevent (description,event_date) values ('GANESH CHATURTHI','2015-08-13');
insert into ved_yearlyevent (description,event_date) values ('SANKATAHARA CHATURTHI','2015-08-13');
insert into ved_yearlyevent (description,event_date) values ('INDEPENDENCE DAY (INDIA)','2015-08-15');
insert into ved_yearlyevent (description,event_date) values ('SANKRANTI (BHADHON)','2015-08-17');
insert into ved_yearlyevent (description,event_date) values ('SRI KRISHAN JANMASHTAMI','2015-08-17');
insert into ved_yearlyevent (description,event_date) values ('EKADASHI (AJA)','2015-08-20');
insert into ved_yearlyevent (description,event_date) values ('SOMVATI AMAVAS','2015-08-25');
insert into ved_yearlyevent (description,event_date) values ('HARTALIKA TEEJ','2015-08-28');
insert into ved_yearlyevent (description,event_date) values ('SIDDHI VINAYAK CHATURTHI','2015-08-29');
insert into ved_yearlyevent (description,event_date) values ('RADHA ASHTAMI','2015-09-02');
insert into ved_yearlyevent (description,event_date) values ('EKADASHI (PADAMA)','2015-09-05');
insert into ved_yearlyevent (description,event_date) values ('ANANT CHATURDASHI','2015-09-07');
insert into ved_yearlyevent (description,event_date) values ('POORNIMA','2015-09-08');
insert into ved_yearlyevent (description,event_date) values ('SATYANARAYAN VRAT','2015-09-08');
insert into ved_yearlyevent (description,event_date) values ('PRATIPADA SHRADDH (PITRI PAKASH)','2015-09-09');
insert into ved_yearlyevent (description,event_date) values ('GANESH CHATURTHI','2015-09-11');
insert into ved_yearlyevent (description,event_date) values ('SANKATAHARA CHATURTHI','2015-09-12');
insert into ved_yearlyevent (description,event_date) values ('SUNDAR KAND','2015-09-13');
insert into ved_yearlyevent (description,event_date) values ('MAHA LAXMI VRAT','2015-09-16');
insert into ved_yearlyevent (description,event_date) values ('SANKRANTI (ASHWIN)','2015-09-16');
insert into ved_yearlyevent (description,event_date) values ('EKADASHI (INDIRA','2015-09-19');
insert into ved_yearlyevent (description,event_date) values ('AMRIT VANI','2015-09-21');
insert into ved_yearlyevent (description,event_date) values ('AMAVAS (SARAV PITRI SHRADDH)','2015-09-23');
insert into ved_yearlyevent (description,event_date) values ('NAVRATRA BEGIN','2015-09-24');
insert into ved_yearlyevent (description,event_date) values ('VISHAL BHAGWATI JAGRAN','2015-09-27');
insert into ved_yearlyevent (description,event_date) values ('DURGA ASHTAMI','2015-10-01');
insert into ved_yearlyevent (description,event_date) values ('MAHANAVAMI','2015-10-02');
insert into ved_yearlyevent (description,event_date) values ('DUSSEHRA','2015-10-03');
insert into ved_yearlyevent (description,event_date) values ('EKADASHI (PAPAMKUSHA)','2015-10-04');
insert into ved_yearlyevent (description,event_date) values ('CHANDI MAHA YAGNA','2015-10-05');
insert into ved_yearlyevent (description,event_date) values ('SATYANARAYAN VRAT','2015-10-07');
insert into ved_yearlyevent (description,event_date) values ('SHARAD POORNIMA','2015-10-07');
insert into ved_yearlyevent (description,event_date) values ('GANESH CHATURTHI','2015-10-11');
insert into ved_yearlyevent (description,event_date) values ('KARVA CHAUTH','2015-10-11');
insert into ved_yearlyevent (description,event_date) values ('SANKATAHARA CHATURTHI','2015-10-11');
insert into ved_yearlyevent (description,event_date) values ('AMRIT VANI','2015-10-12');
insert into ved_yearlyevent (description,event_date) values ('AHOI ASHTAMI','2015-10-15');
insert into ved_yearlyevent (description,event_date) values ('SANKRANTI (KARTIK)','2015-10-17');
insert into ved_yearlyevent (description,event_date) values ('AKHAND RAMAYAN PATH','2015-10-18');
insert into ved_yearlyevent (description,event_date) values ('SUNDAR KAND','2015-10-18');
insert into ved_yearlyevent (description,event_date) values ('EKADASHI (RAMA)','2015-10-19');
insert into ved_yearlyevent (description,event_date) values ('RAMAYAN BHOG','2015-10-19');
insert into ved_yearlyevent (description,event_date) values ('DHAN TRAYODASHI','2015-10-21');
insert into ved_yearlyevent (description,event_date) values ('HANUMAN JAYANTI CELEBRATIONS','2015-10-22');
insert into ved_yearlyevent (description,event_date) values ('DIWALI (AMAVAS)','2015-10-23');
insert into ved_yearlyevent (description,event_date) values ('ANNAKOOT','2015-10-24');
insert into ved_yearlyevent (description,event_date) values ('BHAIYA DOOJ','2015-10-25');
insert into ved_yearlyevent (description,event_date) values ('EKADASHI (DEV PARVODHINI','2015-11-02');
insert into ved_yearlyevent (description,event_date) values ('TULSI VIVAH','2015-11-03');
insert into ved_yearlyevent (description,event_date) values ('POORNIMA','2015-11-06');
insert into ved_yearlyevent (description,event_date) values ('SATYANARAYAN VRAT','2015-11-06');
insert into ved_yearlyevent (description,event_date) values ('SUNDAR KAND','2015-11-08');
insert into ved_yearlyevent (description,event_date) values ('GANESH CHATURTHI','2015-11-09');
insert into ved_yearlyevent (description,event_date) values ('SANKATAHARA CHATURTHI','2015-11-10');
insert into ved_yearlyevent (description,event_date) values ('AMRIT VANI','2015-11-16');
insert into ved_yearlyevent (description,event_date) values ('SANKRANTI (MARG SHIRAS)','2015-11-16');
insert into ved_yearlyevent (description,event_date) values ('EKADASHI (UTPANNA)','2015-11-17');
insert into ved_yearlyevent (description,event_date) values ('AMAVAS','2015-11-22');
insert into ved_yearlyevent (description,event_date) values ('EKADASHI (MOKSHADA)','2015-12-02');
insert into ved_yearlyevent (description,event_date) values ('SATYANARAYAN VRAT','2015-12-05');
insert into ved_yearlyevent (description,event_date) values ('POORNIMA','2015-12-06');
insert into ved_yearlyevent (description,event_date) values ('GANESH CHATURTHI','2015-12-09');
insert into ved_yearlyevent (description,event_date) values ('SANKATAHARA CHATURTHI','2015-12-09');
insert into ved_yearlyevent (description,event_date) values ('SUNDAR KAND','2015-12-13');
insert into ved_yearlyevent (description,event_date) values ('SANKRANTI (PAUSH)','2015-12-16');
insert into ved_yearlyevent (description,event_date) values ('EKADASHI (SAFALA)','2015-12-17');
insert into ved_yearlyevent (description,event_date) values ('AMAVAS','2015-12-21');
insert into ved_yearlyevent (description,event_date) values ('AMRIT VANI','2015-12-21');
